import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  app: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#F6F4EB',
    zIndex: 1,
  },
  header: {
    position: 'absolute',
    top: 0,
    width: '100%',
    backgroundColor: '#F6F4EB',
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 2,
  },
  headerLogo: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#F6F4EB',
    marginRight: 20,
  },
  headerLogoImg: {
    height: 65,
    width: 65,
  },
  headerShopName: {
    marginRight: 10,
    fontSize: 13,
    fontWeight: 'bold',
    color: '#4682A9',
  },
  headerSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#91C8E4',
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  headerSearchBarInput: {
    width: 200,
    padding: 10,
    backgroundColor: 'transparent',
  },
  headerSearchBarIcon: {
    marginLeft: 10,
    color: '#ccc',
  },
  headerAuthButtons: {
    marginRight: 10,
    marginLeft: 10,
    padding: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerAuthButton: {
    marginLeft: 5,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#F6F4EB',
    borderWidth: 0,
    color: '#4682A9',
    borderRadius: 100,
    alignItems: 'center',
    fontSize: 12,
  },
  headerAuthButtonIcon: {
    color: '#4682A9',
  },
  headerDropdown: {
    position: 'relative',
  },
  headerDropdownContent: {
    display: 'none',
    position: 'absolute',
    backgroundColor: '#f9f9f9',
    minWidth: 160,
    boxShadow: '0px 8px 16px 0px rgba(0,0,0,0.2)',
    padding: 12,
    zIndex: 2,
  },
  headerDropdownContentP: {
    color: 'black',
    padding: 12,
  },
  headerDropdownContentPHover: {
    backgroundColor: '#f1f1f1',
  },
  modal: {
    display: 'none',
    position: 'absolute',
    zIndex: 1,
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  modalContent: {
    backgroundColor: '#fefefe',
    margin: '15% auto',
    padding: 20,
    borderWidth: 1,
    borderColor: '#888',
    width: 300,
    borderRadius: 10,
  },
  close: {
    color: '#aaa',
    fontSize: 20,
    fontWeight: 'bold',
  },
  closeHover: {
    color: 'black',
  },
  main: {
    marginTop: 60,
    marginLeft: 220,
    padding: 10,
    flex: 1,
  },
  category: {
    marginVertical: 10,
    fontSize: 15,
    padding: 10,
    backgroundColor: '#629ad3',
    color: 'white',
    textAlign: 'left',
    borderRadius: 25,
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  product: {
    backgroundColor: '#91C8E4',
    borderWidth: 1,
    borderColor: '#ddd',
    width: '30%',
    padding: 10,
    alignItems: 'center',
  },
  productImg: {
    borderRadius: 10,
    marginTop: 20,
    width: '100%',
    height: undefined,
    aspectRatio: 1,
    marginBottom: 10,
  },
  productP: {
    marginVertical: 5,
  },
  mainContainer: {
    flex: 1,
  },
  container: {
    marginTop: 50,
    padding: 30,
  },
  banner: {
    width: '100%',
    height: 200,
    marginBottom: 10,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 1,
  },
  bannerImg: {
    width: '100%',
    height: '80%',
    position: 'absolute',
    top: 80,
    left: 0,
    transition: 'opacity 1s',
  },
  bannerImgHidden: {
    opacity: 0,
  },
  topNavbar: {
    backgroundColor: '#91C8E4',
    height: 60,
    flexDirection: 'row',
    position: 'absolute',
    width: '100%',
    top: 80,
    zIndex: 2,
  },
  hamburger: {
    width: 80,
    backgroundColor: '#629ad3',
    position: 'relative',
    fontSize: 28,
  },
  hamburgerInner: {
    position: 'absolute',
    top: '35%',
    left: '55%',
    width: 40,
    height: 20,
    color: '#0f3249',
  },
  menu: {
    width: 'calc(100% - 80px)',
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  menuLogo: {
    color: '#0f3249',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  sidebar: {
    position: 'absolute',
    top: 140,
    left: 0,
    width: 225,
    height: '100%',
    backgroundColor: '#629ad3',
    zIndex: 1,
  },
  sidebarInner: {
    position: 'relative',
  },
  sidebarLink: {
    color: '#fff',
    fontSize: 14,
    paddingVertical: 20,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 1,
  },
  sidebarLinkIcon: {
    marginRight: 15,
    fontSize: 28,
  },
  sidebarLinkHover: {
    backgroundColor: '#fff',
    color: '#0f3249',
  },
  footer: {
    backgroundColor: '#91C8E4',
    padding: 20,
    color: 'white',
    textAlign: 'center',
  },
  contactInfoFooter: {
    backgroundColor: '#91C8E4',
    height: '20%',
    color: 'white',
    padding: 20,
    textAlign: 'center',
  },
  marqueeText: {
    overflow: 'hidden',
    whiteSpace: 'nowrap',
  },
  marqueeTextP: {
    display: 'inline-block',
    width: '100%',
    paddingLeft: '100%',
  },
  qrcode: {
    marginTop: 150,
    marginLeft: 600,
  },
  qrcodeImg: {
    width: 300,
    height: 300,
  },
  textarea: {
    width: '100%',
    height: 150,
    padding: 12,
    borderWidth: 2,
    borderColor: '#ccc',
    borderRadius: 4,
    backgroundColor: '#f8f8f8',
    fontSize: 16,
  },
  btnApiButton: {
    padding: 10,
    marginTop: 10,
    backgroundColor: '#368fc6',
    color: 'white',
    borderWidth: 0,
    borderRadius: 4,
  },
  btnApiButtonHover: { 
    backgroundColor: '#063357',
  },
  h3: {
    marginTop: 20,
  },
});

export default styles;
